abaplint.json
src/ci/cl_ci_collector_root.clas.abap
src/if_t100_dyn_msg.intf.abap
src/if_t100_dyn_msg.intf.xml

update abaplint to latest + fixes

update abaplint to latest + fixes

---

src/http/if_http_request.intf.abap
src/http/if_http_response.intf.abap

I had added them to wrong interface

Move to response

---

src/http/if_http_entity.intf.abap

Final method used by my attempt to get multipart to work.

Add get_content_type

---

src/if_constraint.intf.abap
src/if_constraint.intf.xml

if_constraint

---

src/alv/cl_gui_alv_grid.clas.abap
src/http/if_http_request.intf.abap

- if_http_request
- cl_gui_alv_grid

Set some parameters to optional

---

src/ci/cl_ci_scan.clas.abap

level, structure, statement, and token

refactoring types

---

src/ci/cl_ci_scan.clas.abap

Ref https://github.com/SAP/code-pal-for-abap/pull/457/files#annotation_1914601593

Adding aunit_tab

---

src/ci/cl_ci_test_root.clas.abap

Ref https://github.com/SAP/code-pal-for-abap/pull/457/files#annotation_1914601593

Adding no_aunit

---

abaplint.json
src/ci/cl_ci_test_scan.clas.abap

https://github.com/abaplint/abaplint/issues/2136

fix p_level

---

src/ixml/if_ixml_document.intf.abap
src/ixml/if_ixml_element.intf.abap

ixml fixes

---

src/icons/icon.type.abap

Add some BW icons

---

src/badi/if_ex_cts_request_check.intf.abap

Add parameter

---

src/ci/cl_ci_test_scan.clas.abap

Ref https://github.com/SAP/code-pal-for-abap/pull/475/checks?check_run_id=3861678515

fix structure_wa

---

src/ixml/if_ixml_document.intf.abap

ref https://github.com/abaplint/abaplint/issues/2284

add create_filter_name_ns

---

src/ixml/if_ixml_document.intf.abap
src/ixml/if_ixml_element.intf.abap

Needed to solve https://github.com/abap2xlsx/abap2xlsx/pull/935/checks?check_run_id=4637904873

+ URI parameter of iXML methods

---

src/ixml/if_ixml_node.intf.abap

to solve lint error https://github.com/abap2xlsx/abap2xlsx/pull/935/checks?check_run_id=4662575539

method get_namespace_uri

---

src/ixml/if_ixml_element.intf.abap

fixes error in https://github.com/abap2xlsx/abap2xlsx/pull/976/checks?check_run_id=4908971235

method  get_attribute_node_ns

---

src/ixml/cl_xml_document.clas.abap

Update cl_xml_document.clas.abap - Display method

---

src/alv/cl_gui_alv_grid.clas.abap

request to include parameters `er_event_data` and `e_fieldname` for event `onf4` of class `cl_gui_alv_grid`.

event f4 new params

---

src/ixml/cl_xml_document.clas.abap

METHODS render_2_string
METHODS create_with_data

new methods cl_xml_document

---

src/alv/cl_gui_alv_grid.clas.abap

Changed parameter type string to char01
Closes #2992

Fix 2992 - Changed parameter type to char01

---

src/ixml/if_ixml_element.intf.abap

https://github.com/abaplint/abaplint/issues/3058

add set_namespace_prefix()

---

src/ixml/if_ixml_document.intf.abap
src/ixml/if_ixml_element.intf.abap
src/ixml/if_ixml_node.intf.abap

I hope it's possible to rename parameter named FOO to NAME and check existing repositories, otherwise I'll revert to FOO, not a problem to me.

IXML complement

---

src/http/if_http_request.intf.abap

Fix if_http_request~set_version

---

src/alv/cl_gui_alv_grid.clas.abap
src/if_os_clone.intf.abap
src/if_os_clone.intf.xml

few fixes for https://github.com/fidley/falv/pull/92

fix parameter name

---

src/gateway/#iwbep#cl_mgw_push_abs_data.clas.abap
src/gateway/#iwbep#if_mgw_appl_srv_runtime.intf.abap
src/gateway/#iwbep#if_mgw_conv_srv_runtime.intf.abap
src/gateway/#iwbep#if_mgw_req_entityset.intf.abap
src/gateway/#iwbep#if_mgw_req_entityset.intf.xml
src/gateway/#iwbep#if_mgw_req_filter.intf.abap
src/gateway/#iwbep#if_mgw_req_filter.intf.xml

this solves the issues here https://github.com/abap2UI5-connectors/fiori-launchpad-kpi-onpremise/blob/2812020ed2cb8a14e964eaab05ad0b7fe0927789/abaplint.jsonc#L10

added some gateway interfaces

---

src/adt/if_oo_adt_intrnl_classrun.intf.abap

if_oo_adt_classrun_out~write has optional name

adding optional name
